from dotenv import load_dotenv
import os


load_dotenv()

ENVIRONMENT = os.getenv("ENVIRONMENT")

HOST = os.getenv("HOST")
PORT = int(os.getenv("PORT"))

POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")

TEST_DB = os.getenv("TEST_DB")
TEST_PORT = os.getenv("TEST_PORT")


PGADMIN_PORT = os.getenv("PGADMIN_PORT")

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")


REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}"

DATABASE_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

DATABASE_TEST_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{TEST_PORT}/{TEST_DB}"


#[AUTH0]
DOMAIN = os.getenv("DOMAIN")
API_AUDIENCE = os.getenv("API_AUDIENCE")
ISSUER = os.getenv("ISSUER")
ALGORITHMS = os.getenv("ALGORITHMS")

JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
JWT_REFRESH_SECRET_KEY = os.getenv("JWT_REFRESH_SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
ACCES_TOKEN_EXPIRE_MINUTES = os.getenv("ACCES_TOKEN_EXPIRE_MINUTES")
REFRESH_TOKEN_EXPIRE_MINUTES = os.getenv("REFRESH_TOKEN_EXPIRE_MINUTES")