"""migration_11

Revision ID: 0c16691789d0
Revises: a21351ca9ac1
Create Date: 2023-03-26 01:08:27.614738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c16691789d0'
down_revision = 'a21351ca9ac1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_table', 'action_id')
    op.drop_column('member_table', 'member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_table', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('action_table', sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
