"""migration_2

Revision ID: 296f32a5ac47
Revises: 185230f15f5c
Create Date: 2023-03-20 03:03:57.205206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296f32a5ac47'
down_revision = '185230f15f5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_table',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_description', sa.String(length=250), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user_table.user_id'], ),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('company_description'),
    sa.UniqueConstraint('company_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_table')
    # ### end Alembic commands ###
