"""m2

Revision ID: 3c02b80d2195
Revises: d18f41f67129
Create Date: 2023-02-28 23:46:20.315483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c02b80d2195'
down_revision = 'd18f41f67129'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
