"""migration_3

Revision ID: 41bda6d1123b
Revises: 296f32a5ac47
Create Date: 2023-03-20 13:06:49.457307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41bda6d1123b'
down_revision = '296f32a5ac47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
