"""migration_8

Revision ID: 594b6adee97e
Revises: b2d11f7131d7
Create Date: 2023-03-25 19:23:12.599642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594b6adee97e'
down_revision = 'b2d11f7131d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_table', sa.Column('user_role', sa.String(), nullable=True))
    op.drop_column('member_table', 'action_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_table', sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('member_table', 'user_role')
    # ### end Alembic commands ###
