"""migration_8

Revision ID: 7f60ca8cb33f
Revises: 594b6adee97e
Create Date: 2023-03-26 00:12:32.445473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f60ca8cb33f'
down_revision = '594b6adee97e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
