"""migration_4

Revision ID: 96c47f9a1c84
Revises: 41bda6d1123b
Create Date: 2023-03-20 14:04:39.817348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c47f9a1c84'
down_revision = '41bda6d1123b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_table_company_description_key', 'company_table', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('company_table_company_description_key', 'company_table', ['company_description'])
    # ### end Alembic commands ###
