"""migration_9

Revision ID: 97acd8c1d141
Revises: 7f60ca8cb33f
Create Date: 2023-03-26 00:28:30.568765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97acd8c1d141'
down_revision = '7f60ca8cb33f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('action_table_company_id_fkey', 'action_table', type_='foreignkey')
    op.create_foreign_key(None, 'action_table', 'company_table', ['company_id'], ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action_table', type_='foreignkey')
    op.create_foreign_key('action_table_company_id_fkey', 'action_table', 'company_table', ['company_id'], ['company_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
