"""migration_10

Revision ID: a21351ca9ac1
Revises: 97acd8c1d141
Create Date: 2023-03-26 01:05:11.814589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21351ca9ac1'
down_revision = '97acd8c1d141'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
