"""migration_7

Revision ID: b2d11f7131d7
Revises: 0c63007e0887
Create Date: 2023-03-25 19:19:56.205951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d11f7131d7'
down_revision = '0c63007e0887'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_table',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_table.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], ),
    sa.PrimaryKeyConstraint('action_id', 'user_id', 'company_id')
    )
    op.create_table('member_table',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_table.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], ),
    sa.PrimaryKeyConstraint('member_id', 'user_id', 'company_id')
    )
    op.drop_constraint('company_table_owner_id_fkey', 'company_table', type_='foreignkey')
    op.create_foreign_key(None, 'company_table', 'user_table', ['owner_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_table', type_='foreignkey')
    op.create_foreign_key('company_table_owner_id_fkey', 'company_table', 'user_table', ['owner_id'], ['user_id'])
    op.drop_table('member_table')
    op.drop_table('action_table')
    # ### end Alembic commands ###
