"""migration_5

Revision ID: f0331c5a9553
Revises: 96c47f9a1c84
Create Date: 2023-03-20 14:09:29.377019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0331c5a9553'
down_revision = '96c47f9a1c84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
