"""migration_13

Revision ID: f0fc04a95400
Revises: 0c16691789d0
Create Date: 2023-03-27 17:08:35.725184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fc04a95400'
down_revision = '0c16691789d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_table', sa.Column('action_id', sa.Integer(), nullable=False))
    op.alter_column('action_table', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('action_table', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('member_table', sa.Column('member_id', sa.Integer(), nullable=False))
    op.alter_column('member_table', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('member_table', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_table', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('member_table', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('member_table', 'member_id')
    op.alter_column('action_table', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('action_table', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('action_table', 'action_id')
    # ### end Alembic commands ###
